### ISSUE TITLE
关于阅读本文所需要的基本理解？

### ISSUE THREAD

**Issue by Guanys-dar** [shwangtangjun/Diff-ResNet#1]
感谢精彩的工作。
但是作为外行，想要阅读清楚本文需要先阅读哪些前置工作？
以及本文diffusion机制的核心动机是什么，resblock为什么被称为convection block？
是否能给一些阅读本文的引导和建议呢？
十分感谢。

**Comment by shwangtangjun** [comment]
前置工作主要有两方面：一方面是图神经网络(GNN)领域的论文如GCN,GAT等，另一方面是常微分方程(ODE)与神经网络的关系，如Neural ODE。
核心动机是通过diffusion引入标注和未标注数据之间的联系，从而处理在标注数据稀缺情况下的分类问题。residual block被称为convection block的原因是，dx/dt=f(x,t)对应于convection-diffusion equation里的convection部分。
阅读本文时如果遇到困难，欢迎沟通，不过最好使用邮箱，github可以用于讨论代码问题。
